name: MCAC
main: uk.co.crashcraft.mcma.Main
version: 1.0
author: Crashdoom
commands:
  test:
    description: testing
    usage: /<command>
  disable:
    description: testing
    usage: /<command>